---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc5
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-ceph-hdd-dp1